load("//tools:openscad.bzl", "scad_part")

scad_part(
    name = "gearmotor",
    file = "gearmotor.scad",
    toplevel = "$fn=100;gearmotor();",
)

scad_part(
    name = "motor",
    file = "gearmotor.scad",
    toplevel = "$fn=100;motor();",
)

scad_part(
    name = "gearbox",
    file = "gearmotor.scad",
    toplevel = "$fn=100;gearbox();",
)
