version: 2
jobs:
  build:
    docker:
      - image: justbuchanan/docker-archlinux
    steps:
      - run: echo 'export GOPATH=$HOME/go' >> $BASH_ENV
      - run: echo 'export PATH=$GOPATH/bin:$PATH' >> $BASH_ENV

      - run: mkdir /tmp/artifacts
      - run: echo 'export CIRCLE_ARTIFACTS=/tmp/artifacts' >> $BASH_ENV

      - run: pacman -Sy --noconfirm bazel openscad clang python python-pip git go openssh
      - run: go get -u github.com/justbuchanan/ci-status

      # TODO: bazel should handle this
      - run: pip install sympy

      - checkout

      - run: bazel query //...

      - run: echo "export SCAD_MODELS=\"$(bazel query 'filter(.*_scad,...)')\"" >> $BASH_ENV
      - run: echo $SCAD_MODELS
      - run: bazel build $SCAD_MODELS
      # - run: >-
      #     ci-status
      #     --context generate_scad
      #     --description "Generate scad from solidpy"
      #     "bazel build \"$SCAD_MODELS\""

      - run: >-
          ci-status
          --context render_svgs
          --description "Render all SVGs"
          "bazel build $(bazel query 'filter(.*_svg,...)')"

      - store_artifacts:
          path: bazel-bin
      - store_artifacts:
          path: /tmp/artifacts

workflows:
  version: 2
  all:
    jobs:
      - build
