version: 2
jobs:
  build:
    docker:
      - image: justbuchanan/docker-archlinux
    steps:
      - run: echo 'export GOPATH=$HOME/go' >> $BASH_ENV
      - run: echo 'export PATH=$GOPATH/bin:$PATH' >> $BASH_ENV

      - run: mkdir /tmp/artifacts
      - run: echo 'export CIRCLE_ARTIFACTS=/tmp/artifacts' >> $BASH_ENV

      - run: pacman -Sy --noconfirm bazel openscad clang python python-pip git go openssh
      - run: go get -u github.com/justbuchanan/ci-status

      - checkout

      - run: ci-status --context planter --description "Render all SVGs" "bazel build $(bazel query 'filter(.*_svg,...)')"
      - run: ci-status --context planter --description "Generate alll .scad files" "bazel build $(bazel query 'filter(.*_scad,...)')"

      - store_artifacts:
          path: bazel-bin
      - store_artifacts:
          path: /tmp/artifacts

workflows:
  version: 2
  all:
    jobs:
      - build
