version: 2
jobs:
  build:
    docker:
      - image: justbuchanan/docker-archlinux
    steps:
      - run: echo 'export GOPATH=$HOME/go' >> $BASH_ENV
      - run: echo 'export PATH=$GOPATH/bin:$PATH' >> $BASH_ENV

      - run: mkdir /tmp/artifacts
      - run: echo 'export CIRCLE_ARTIFACTS=/tmp/artifacts' >> $BASH_ENV

      - run: pacman -Sy --noconfirm bazel openscad clang python python-pip git go openssh
      - run: go get -u github.com/justbuchanan/ci-status

      # TODO: bazel should handle this
      - run: pip install sympy

      - checkout

      - run: bazel query //...

      - run: echo "export SCAD_MODELS=\"$(bazel query 'filter(.*_scad,...)')\"" >> $BASH_ENV
      - run: echo $SCAD_MODELS
      - run: bazel build $SCAD_MODELS
      # - run: >-
      #     ci-status
      #     --context generate_scad
      #     --description "Generate scad from solidpy"
      #     "bazel build \"$SCAD_MODELS\""

      - run: >-
          ci-status
          --context render_svgs
          --description "Render all SVGs"
          "bazel build $(bazel query 'filter(.*_svg,...)')"

      - store_artifacts:
          path: bazel-bin
      - store_artifacts:
          path: /tmp/artifacts



  build_cq:
    working_directory: /cadquery-models
    docker:
      - image: justbuchanan/docker-cadquery
    steps:
      - run: mkdir /tmp/artifacts
      - run: echo 'export CIRCLE_ARTIFACTS=/tmp/artifacts' >> $BASH_ENV

      - checkout

      # system deps
      - run: echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | tee /etc/apt/sources.list.d/bazel.list
      - run: curl https://bazel.build/bazel-release.pub.gpg | apt-key add -
      - run: apt-get update
      - run: apt -y install openjdk-8-jdk bazel

      - run: bazel query //...
      - run: bazel build //cq_example:block_stl
      # - run: bazel build //cq_example:car_gltf

      - store_artifacts:
          path: /tmp/artifacts
      - save_cache:
          key: artifacts-{{ .Branch }}-{{ .Revision }}
          paths:
              - "/tmp/artifacts"



workflows:
  version: 2
  all:
    jobs:
      - build
      - build_cq
