load("//tools:openscad.bzl", "scad_part")

scad_part(
    name = "part1",
    file = "multipart.scad",
    toplevel = "test1(3)",
)

scad_part(
    name = "part2",
    file = "multipart.scad",
    toplevel = "test1(9)",
)
