load("//tools:tools.bzl", "solidpy_model")

solidpy_model(
    name = "planter",
    file = "round_rect_pot.py",
)

solidpy_model(
    name = "planter_old",
    file = "planter_old.py",
    scad_resolution = 100,
)
