load("//tools:solidpy.bzl", "solidpy_model")

solidpy_model(
    name = "downspout_connector",
    file = "downspout_connector.py",
    py_deps = [
        "//tools:util_py",
    ],
    scad_resolution = 100,
    deps = [
        # "@mcad",
        "@scad_utils",
    ],
)
